### ISSUE TITLE
propose of including soot 

### ISSUE THREAD

**Issue by jimmyMaci** [lightblueseas/xml-extensions#5]
Hi there,

can you include soot to the Project for analyze and optimize Java Code:

```
<dependency>
    <groupId>ca.mcgill.sable</groupId>
    <artifactId>soot</artifactId>
    <version>3.3.0</version>
</dependency>
```
Cheers
James Phelps

**Comment by astrapi69** [comment]
Hi @jimmyMaci, please provide a PR with a description for what is it useful for this project. I will close this issue
